### ISSUE TITLE
undefined-reflect.VisibleFields

### ISSUE THREAD

**Issue by ulikestyle** [ryanc414/etherscan-api-go#1]
![image](https://user-images.githubusercontent.com/26086585/142396955-ecfb9140-4efa-40a9-8a3f-90d4f88af540.png)

unmarshallers.go 
-  undefined: reflect.VisibleFields
你好，这里有个报错

**Comment by ryanc414** [comment]
reflect.VisibleFields was added to the stdlib in Go 1.17, I suggest updating to the latest Go version and trying again.

**Comment by ulikestyle** [comment]
> reflect.VisibleFields was added to the stdlib in Go 1.17, I suggest updating to the latest Go version and trying again.

ok, thank you. i will upgrade my go version
